/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentacion;

import negocio.GestorVehiculoPersona;
import negocio.Persona;
import negocio.Vehiculo;

/**
 *
 * @author Personal
 */
public class GUIAsociarVehPersona extends javax.swing.JInternalFrame {
    private GestorVehiculoPersona gestorVehiculo = new GestorVehiculoPersona();
    private int atrCodCarne;
    private String atrPlacaVeh;
    /**
     * Creates new form GUIAsociarVehPersona
     */
    public GUIAsociarVehPersona() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        lbCodCarne = new javax.swing.JLabel();
        txtCodCarne = new javax.swing.JTextField();
        lbPlacaVeh = new javax.swing.JLabel();
        txtPlacaVeh = new javax.swing.JFormattedTextField();
        lbGuardarInfo = new javax.swing.JLabel();
        btnRegistrar = new javax.swing.JButton();

        jPanel2.setLayout(new java.awt.GridLayout(3, 2));

        lbCodCarne.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        lbCodCarne.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbCodCarne.setText("Código de Carné: ");
        jPanel2.add(lbCodCarne);
        jPanel2.add(txtCodCarne);

        lbPlacaVeh.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        lbPlacaVeh.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbPlacaVeh.setText("Placa Vehiculo: ");
        jPanel2.add(lbPlacaVeh);
        jPanel2.add(txtPlacaVeh);

        lbGuardarInfo.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        lbGuardarInfo.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbGuardarInfo.setText("Guardar Información");
        jPanel2.add(lbGuardarInfo);

        btnRegistrar.setText("Registrar");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });
        jPanel2.add(btnRegistrar);

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        // TODO add your handling code here:
        int codCarnet = getAtrCodCarne();
        String placaVeh = getAtrPlacaVeh();
        String respuesta;
        Persona persona = gestorVehiculo.buscarUsuarioCarne(codCarnet);
        if (persona != null){
            Vehiculo vehiculo = gestorVehiculo.buscarVehPlaca(placaVeh);
            if (vehiculo != null){
                respuesta = gestorVehiculo.registrarAsociacion(persona.getPerIdentificacion(), atrCodCarne, placaVeh);
                if (respuesta.equals("Asociacion registrada con exito")){
                    Utilidades.Utilidades.mensajeExito(respuesta, "Exito");
                }else{
                  Utilidades.Utilidades.mensajeError(respuesta, "Error");  
                }
            }else{
                Utilidades.Utilidades.mensajeAdvertencia("Placa Vehiculo NO registrada", "Advertencia");
            }
        }else{
            Utilidades.Utilidades.mensajeAdvertencia("Usuario NO registrada", "Advertencia");
        }
               
    }//GEN-LAST:event_btnRegistrarActionPerformed
    public int getAtrCodCarne() {
        atrCodCarne = Integer.parseInt(txtCodCarne.getText());
        return atrCodCarne;
    }

    public String getAtrPlacaVeh() {
        atrPlacaVeh = txtPlacaVeh.getText();
        return atrPlacaVeh;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lbCodCarne;
    private javax.swing.JLabel lbGuardarInfo;
    private javax.swing.JLabel lbPlacaVeh;
    private javax.swing.JTextField txtCodCarne;
    private javax.swing.JFormattedTextField txtPlacaVeh;
    // End of variables declaration//GEN-END:variables
}
