/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentacion;

import Utilidades.Utilidades;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import negocio.GestorParqueadero;
import negocio.Multa;
import negocio.Reporte;

/**
 *
 * @author oscar
 */
public class GUIReporteIngreso extends javax.swing.JInternalFrame {

    /**
     * Creates new form GUIReporteIngreso
     */
    public GUIReporteIngreso(String prmPlaca) {
        initComponents();
        verReporte(prmPlaca);
        lblplaca.setText(prmPlaca);
        
    }
    public boolean verReporte(String prmPlaca){
       
        GestorParqueadero gestor = new GestorParqueadero();
        ArrayList<Reporte> objre = null;
        objre = gestor.reporteIngresoVeh(prmPlaca);
        if (objre != null){
            if(cargarReporte(objre)){
                return true;
            }   
        }
        return false;
    }
    public boolean cargarReporte(ArrayList<Reporte> prmReporte){
        DefaultTableModel model = (DefaultTableModel) tblReporteIngreso.getModel();
        Object rowData[] = new Object[2];
        int cont=2;
        int cont1=1;
        for (Reporte re : prmReporte) {
            rowData[0] = "semana "+cont1;
            rowData[1] = re.getCantidad();
            model.addRow(rowData);
            cont--;
            cont1++;
        }
        if(cont==2){
            
            return false;
        }
        return true;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlreporteIngreso = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblReporteIngreso = new javax.swing.JTable();
        lblTitulo = new javax.swing.JLabel();
        lblplaca = new javax.swing.JLabel();

        setClosable(true);

        pnlreporteIngreso.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        tblReporteIngreso.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Semana", "Cantidad"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblReporteIngreso);

        lblTitulo.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblTitulo.setText("Reporte Ingreso    Placa:  ");

        lblplaca.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        javax.swing.GroupLayout pnlreporteIngresoLayout = new javax.swing.GroupLayout(pnlreporteIngreso);
        pnlreporteIngreso.setLayout(pnlreporteIngresoLayout);
        pnlreporteIngresoLayout.setHorizontalGroup(
            pnlreporteIngresoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlreporteIngresoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlreporteIngresoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlreporteIngresoLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 411, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlreporteIngresoLayout.createSequentialGroup()
                        .addComponent(lblTitulo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblplaca, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnlreporteIngresoLayout.setVerticalGroup(
            pnlreporteIngresoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlreporteIngresoLayout.createSequentialGroup()
                .addGroup(pnlreporteIngresoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTitulo)
                    .addComponent(lblplaca, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlreporteIngreso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlreporteIngreso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblplaca;
    private javax.swing.JPanel pnlreporteIngreso;
    private javax.swing.JTable tblReporteIngreso;
    // End of variables declaration//GEN-END:variables
}
