/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentacion;

import negocio.GestorVehiculoPersona;
import negocio.Vehiculo;

/**
 *
 * @author Personal
 */
public class GUIRegistrarVehiculo extends javax.swing.JInternalFrame {
    private final GestorVehiculoPersona gestorVehiculo = new GestorVehiculoPersona();
    private int idConductor;
    private int codCarne;
    private String placaVehiculo, marca, tipoVehiculo;
    /**
     * Creates new form GUIRegPersona
     */
    public GUIRegistrarVehiculo(int prmConductor, int prmCodCarne) {
        initComponents();
        setVisible(true);
        idConductor = prmConductor;
        txtIdPropietario.setText(Integer.toString(idConductor));
        codCarne = prmCodCarne;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlPrincipal = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        lbRegConductor = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtIdPropietario = new javax.swing.JTextField();
        lbNroPlaca = new javax.swing.JLabel();
        txtPlaca = new javax.swing.JTextField();
        lbMarca = new javax.swing.JLabel();
        txtMarca = new javax.swing.JTextField();
        lbTipoVehiculo = new javax.swing.JLabel();
        cbTipoVehiculo = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        btnRegVehiculo = new javax.swing.JButton();

        setClosable(true);

        pnlPrincipal.setBackground(new java.awt.Color(204, 204, 204));
        pnlPrincipal.setLayout(new java.awt.GridLayout(11, 1));

        jPanel4.setBackground(new java.awt.Color(51, 153, 255));
        jPanel4.setLayout(new java.awt.GridLayout(1, 1));

        lbRegConductor.setBackground(new java.awt.Color(0, 153, 255));
        lbRegConductor.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbRegConductor.setForeground(new java.awt.Color(255, 255, 255));
        lbRegConductor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbRegConductor.setText("Registrar Vehiculo");
        jPanel4.add(lbRegConductor);

        pnlPrincipal.add(jPanel4);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Identificacion Propietario");
        pnlPrincipal.add(jLabel2);

        txtIdPropietario.setEditable(false);
        txtIdPropietario.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        pnlPrincipal.add(txtIdPropietario);

        lbNroPlaca.setBackground(new java.awt.Color(204, 204, 255));
        lbNroPlaca.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbNroPlaca.setText("No. de Placa");
        pnlPrincipal.add(lbNroPlaca);
        pnlPrincipal.add(txtPlaca);

        lbMarca.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbMarca.setText("Marca");
        pnlPrincipal.add(lbMarca);
        pnlPrincipal.add(txtMarca);

        lbTipoVehiculo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbTipoVehiculo.setText("Tipo de Vehiculo");
        pnlPrincipal.add(lbTipoVehiculo);

        cbTipoVehiculo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Vehiculo", "Motocicleta" }));
        pnlPrincipal.add(cbTipoVehiculo);
        pnlPrincipal.add(jLabel1);

        btnRegVehiculo.setBackground(new java.awt.Color(204, 204, 255));
        btnRegVehiculo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnRegVehiculo.setText("Registrar Vehiculo");
        btnRegVehiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegVehiculoActionPerformed(evt);
            }
        });
        pnlPrincipal.add(btnRegVehiculo);

        getContentPane().add(pnlPrincipal, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegVehiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegVehiculoActionPerformed
        // TODO add your handling code here:
        int idConductor;
        int codCarne;
        String placa, marca, tipoVehiculo, confirmacion;
        codCarne = getCodCarne();
        placa = getPlaca();
        marca = getMarca();
        tipoVehiculo = getTipoVehiculo();
        idConductor = getIdConductor();
        Vehiculo objVehiculo = new Vehiculo(idConductor,codCarne, placa, marca, tipoVehiculo);
        confirmacion = gestorVehiculo.registrarVehiculo(objVehiculo);
        Utilidades.Utilidades.mensajeExito(confirmacion, "Registro Exitoso.");
        this.dispose();
        
    }//GEN-LAST:event_btnRegVehiculoActionPerformed

    public int getCodCarne() {
        return codCarne;
    }

    public void setCodCarne(int codCarne) {
        this.codCarne = codCarne;
    }
    
    public int getIdConductor(){
        return idConductor;
    }
    public String getPlaca(){
        placaVehiculo = txtPlaca.getText();
        return placaVehiculo;
    }
    public String getMarca(){
        marca = txtMarca.getText();
        return marca;
    }
    public String getTipoVehiculo(){
        int i;
        if (cbTipoVehiculo.getSelectedIndex() == 0){
            tipoVehiculo = "Automovil";
        }
        if(cbTipoVehiculo.getSelectedIndex() == 1){
            tipoVehiculo = "Motocicleta";
        }
        return tipoVehiculo;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegVehiculo;
    private javax.swing.JComboBox<String> cbTipoVehiculo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel lbMarca;
    private javax.swing.JLabel lbNroPlaca;
    private javax.swing.JLabel lbRegConductor;
    private javax.swing.JLabel lbTipoVehiculo;
    private javax.swing.JPanel pnlPrincipal;
    private javax.swing.JTextField txtIdPropietario;
    private javax.swing.JTextField txtMarca;
    private javax.swing.JTextField txtPlaca;
    // End of variables declaration//GEN-END:variables
}
