/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentacion;

import java.text.DateFormat;
import java.util.Date;
import negocio.GestorUsuario;
import negocio.GestorVehiculoPersona;
import negocio.Persona;

/**
 *
 * @author Personal
 */
public class GUIRegistrarConductor extends javax.swing.JInternalFrame {

    private int codCarne, identificacion;
    private String nombre, apellido, genero, fechaNacimiento, rol;
    private final GestorVehiculoPersona gestorVehPersona = new GestorVehiculoPersona();

    /**
     * Creates new form GUIRegPersona
     */
    public GUIRegistrarConductor(int prmIdpersona,String tipo) {
        initComponents();
        setVisible(true);
        if(tipo.equals("carnet")){
             codCarne = prmIdpersona;
             txtCodCarne.setText(Integer.toString(prmIdpersona));
             txtCodCarne.setEnabled(false);           
        }else{
             identificacion = prmIdpersona;
             txtId.setText(Integer.toString(prmIdpersona));
             txtId.setEnabled(false);           
        }
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlPrincipal = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        lbRegConductor = new javax.swing.JLabel();
        lbIdentificacion = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        lblCodCarne = new javax.swing.JLabel();
        txtCodCarne = new javax.swing.JTextField();
        lbNombres = new javax.swing.JLabel();
        txtNombres = new javax.swing.JTextField();
        lbApellidos = new javax.swing.JLabel();
        txtApellidos = new javax.swing.JTextField();
        lbGenero = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        rbFemenino = new javax.swing.JRadioButton();
        rbMasculino = new javax.swing.JRadioButton();
        rbOtro = new javax.swing.JRadioButton();
        lbFecNacimiento = new javax.swing.JLabel();
        rSDateCalendar = new com.toedter.calendar.JDateChooser();
        lbRol = new javax.swing.JLabel();
        cbRol = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        btnRegConductor = new javax.swing.JButton();

        setClosable(true);
        setMaximizable(true);

        pnlPrincipal.setBackground(new java.awt.Color(204, 204, 204));
        pnlPrincipal.setLayout(new java.awt.GridLayout(17, 1));

        jPanel4.setBackground(new java.awt.Color(51, 153, 255));
        jPanel4.setLayout(new java.awt.GridLayout(1, 1));

        lbRegConductor.setBackground(new java.awt.Color(0, 153, 255));
        lbRegConductor.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbRegConductor.setForeground(new java.awt.Color(255, 255, 255));
        lbRegConductor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbRegConductor.setText("Registro de Conductor");
        jPanel4.add(lbRegConductor);

        pnlPrincipal.add(jPanel4);

        lbIdentificacion.setBackground(new java.awt.Color(204, 204, 255));
        lbIdentificacion.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbIdentificacion.setText("Identificación");
        pnlPrincipal.add(lbIdentificacion);

        txtId.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtIdKeyTyped(evt);
            }
        });
        pnlPrincipal.add(txtId);

        lblCodCarne.setText("Código Carné");
        pnlPrincipal.add(lblCodCarne);
        pnlPrincipal.add(txtCodCarne);

        lbNombres.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbNombres.setText("Nombres");
        pnlPrincipal.add(lbNombres);
        pnlPrincipal.add(txtNombres);

        lbApellidos.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbApellidos.setText("Apellidos");
        pnlPrincipal.add(lbApellidos);
        pnlPrincipal.add(txtApellidos);

        lbGenero.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbGenero.setText("Genero");
        pnlPrincipal.add(lbGenero);

        jPanel2.setLayout(new java.awt.GridLayout(1, 3));

        rbFemenino.setSelected(true);
        rbFemenino.setText("Femenino");
        jPanel2.add(rbFemenino);

        rbMasculino.setText("Masculino");
        jPanel2.add(rbMasculino);

        rbOtro.setText("Otro");
        jPanel2.add(rbOtro);

        pnlPrincipal.add(jPanel2);

        lbFecNacimiento.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbFecNacimiento.setText("Fecha de Nacimiento");
        pnlPrincipal.add(lbFecNacimiento);
        pnlPrincipal.add(rSDateCalendar);

        lbRol.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbRol.setText("Rol");
        pnlPrincipal.add(lbRol);

        cbRol.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Estudiante", "Docente" }));
        pnlPrincipal.add(cbRol);
        pnlPrincipal.add(jLabel1);

        btnRegConductor.setBackground(new java.awt.Color(204, 204, 255));
        btnRegConductor.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnRegConductor.setText("Registrar Conductor");
        btnRegConductor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegConductorActionPerformed(evt);
            }
        });
        pnlPrincipal.add(btnRegConductor);

        getContentPane().add(pnlPrincipal, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtIdKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIdKeyTyped
        // TODO add your handling code here:
        char car = evt.getKeyChar();
        if ((car < '0' || car > '9') && (car < ',' || car > '.')) {
            evt.consume();
        }
    }//GEN-LAST:event_txtIdKeyTyped

    private void btnRegConductorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegConductorActionPerformed
        // TODO add your handling code here:
        String confirmacion;
        int id=getIdentificacion();
        int codCarne = getCodCarne();
        String nombre = getNombre();
        String apellido = getApellido();
        String genero = getGenero();
        String fechaNacimiento = getFechaNacimiento();
        String rol = getRol();
        Persona conductor = gestorVehPersona.buscarUsuarioDocumento(id);
        Persona cond= gestorVehPersona.buscarUsuarioCarne(codCarne);
        if (conductor == null && cond==null) {
            conductor = new Persona(identificacion, codCarne, nombre, apellido, genero, fechaNacimiento, rol);
            confirmacion = gestorVehPersona.registrarConductor(conductor);
            Utilidades.Utilidades.mensajeExito(confirmacion, "Registro Exitoso.");
            this.dispose();
        } else {
            Utilidades.Utilidades.mensajeError("El Conductor con esa identificación o codigo de carne ya se encuentra registrado.", "Advertencia");
        }


    }//GEN-LAST:event_btnRegConductorActionPerformed
    public int getCodCarne() {
        codCarne = Integer.parseInt(txtCodCarne.getText());
        return codCarne;
    }

    public String getNombre() {
        nombre = txtNombres.getText();
        return nombre;
    }

    public String getApellido() {
        apellido = txtApellidos.getText();
        return apellido;
    }
    public int getIdentificacion(){
        identificacion=Integer.parseInt(txtId.getText());
        return identificacion;
    }

    public String getGenero() {
        if (rbFemenino.isSelected()) {
            genero = "Femenino";
        }
        if (rbMasculino.isSelected()) {
            genero = "Masculino";
        }
        if (rbOtro.isSelected()) {
            genero = "Otro";
        }
        return genero;
    }

    public String getFechaNacimiento() {
        Date date = rSDateCalendar.getDate();
        fechaNacimiento = DateFormat.getDateInstance().format(date);
        return fechaNacimiento;
    }

    public String getRol() {
        int i;
        i = cbRol.getSelectedIndex();
        if (i == 0) {
            rol = "Estudiante";
        }
        if (i == 1) {
            rol = "Docente";
        }
        return rol;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegConductor;
    private javax.swing.JComboBox<String> cbRol;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel lbApellidos;
    private javax.swing.JLabel lbFecNacimiento;
    private javax.swing.JLabel lbGenero;
    private javax.swing.JLabel lbIdentificacion;
    private javax.swing.JLabel lbNombres;
    private javax.swing.JLabel lbRegConductor;
    private javax.swing.JLabel lbRol;
    private javax.swing.JLabel lblCodCarne;
    private javax.swing.JPanel pnlPrincipal;
    private com.toedter.calendar.JDateChooser rSDateCalendar;
    private javax.swing.JRadioButton rbFemenino;
    private javax.swing.JRadioButton rbMasculino;
    private javax.swing.JRadioButton rbOtro;
    private javax.swing.JTextField txtApellidos;
    private javax.swing.JTextField txtCodCarne;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtNombres;
    // End of variables declaration//GEN-END:variables
}
