/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentacion;

import java.text.DateFormat;
import java.util.Date;
import negocio.GestorUsuario;
import negocio.Vigilante;

/**
 *
 * @author Personal
 */
public class GUIRegistrarVigilante extends javax.swing.JInternalFrame {

    private String identificacion, nombre, apellido, genero, fechaNacimiento, empresa, usuario, contrasenia;
    private final GestorUsuario gestorVigilante = new GestorUsuario();

    public GUIRegistrarVigilante() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlPrincipal = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        lbRegConductor = new javax.swing.JLabel();
        lbIdentificacion = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        lbNombres = new javax.swing.JLabel();
        txtNombres = new javax.swing.JTextField();
        lbApellidos = new javax.swing.JLabel();
        txtApellidos = new javax.swing.JTextField();
        lbGenero = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        rbFemenino = new javax.swing.JRadioButton();
        rbMasculino = new javax.swing.JRadioButton();
        rbOtro = new javax.swing.JRadioButton();
        lbFecNacimiento = new javax.swing.JLabel();
        rSDateCalendar = new com.toedter.calendar.JDateChooser();
        lbEmpresa = new javax.swing.JLabel();
        txtEmpresa = new javax.swing.JTextField();
        lblUsuario = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtContrasenia = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btnRegVigilante = new javax.swing.JButton();

        setClosable(true);

        pnlPrincipal.setBackground(new java.awt.Color(204, 204, 204));
        pnlPrincipal.setLayout(new java.awt.GridLayout(19, 1));

        jPanel4.setBackground(new java.awt.Color(51, 153, 255));
        jPanel4.setLayout(new java.awt.GridLayout(1, 1));

        lbRegConductor.setBackground(new java.awt.Color(0, 153, 255));
        lbRegConductor.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbRegConductor.setForeground(new java.awt.Color(255, 255, 255));
        lbRegConductor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbRegConductor.setText("Registro de Vigilante");
        jPanel4.add(lbRegConductor);

        pnlPrincipal.add(jPanel4);

        lbIdentificacion.setBackground(new java.awt.Color(204, 204, 255));
        lbIdentificacion.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbIdentificacion.setText("Identificación");
        pnlPrincipal.add(lbIdentificacion);

        txtId.setText("2");
        pnlPrincipal.add(txtId);

        lbNombres.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbNombres.setText("Nombres");
        pnlPrincipal.add(lbNombres);

        txtNombres.setText("Andres");
        pnlPrincipal.add(txtNombres);

        lbApellidos.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbApellidos.setText("Apellidos");
        pnlPrincipal.add(lbApellidos);

        txtApellidos.setText("Lopez");
        pnlPrincipal.add(txtApellidos);

        lbGenero.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbGenero.setText("Genero");
        pnlPrincipal.add(lbGenero);

        jPanel2.setLayout(new java.awt.GridLayout(1, 3));

        rbFemenino.setText("Femenino");
        jPanel2.add(rbFemenino);

        rbMasculino.setText("Masculino");
        jPanel2.add(rbMasculino);

        rbOtro.setText("Otro");
        jPanel2.add(rbOtro);

        pnlPrincipal.add(jPanel2);

        lbFecNacimiento.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbFecNacimiento.setText("Fecha de Nacimiento");
        pnlPrincipal.add(lbFecNacimiento);
        pnlPrincipal.add(rSDateCalendar);

        lbEmpresa.setText("Empresa");
        pnlPrincipal.add(lbEmpresa);

        txtEmpresa.setText("Limitada S.A");
        pnlPrincipal.add(txtEmpresa);

        lblUsuario.setText("Usuario");
        pnlPrincipal.add(lblUsuario);

        txtUsuario.setText("alopez");
        pnlPrincipal.add(txtUsuario);

        jLabel2.setText("Contraseña");
        pnlPrincipal.add(jLabel2);

        txtContrasenia.setText("123");
        pnlPrincipal.add(txtContrasenia);
        pnlPrincipal.add(jLabel1);

        btnRegVigilante.setBackground(new java.awt.Color(204, 204, 255));
        btnRegVigilante.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnRegVigilante.setText("Registrar");
        btnRegVigilante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegVigilanteActionPerformed(evt);
            }
        });
        pnlPrincipal.add(btnRegVigilante);

        getContentPane().add(pnlPrincipal, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegVigilanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegVigilanteActionPerformed
        // TODO add your handling code here:
        String confirmacion;
        String identificacion = getIdentificacion();
        String nombreV = getNombre();
        String apellidoV = getApellido();
        String generoV = getGenero();
        String fechaNacimientoV = getFechaNacimiento();
        String empresaV = getEmpresa();
        String usuarioV = getUsuario();
        String contraseniaV = getContrasenia();
        Vigilante vigilante = new Vigilante(identificacion, nombreV, apellidoV, generoV, fechaNacimientoV, empresaV, usuarioV, contraseniaV);
        confirmacion = gestorVigilante.registrarVigilante(vigilante);
        if (confirmacion.equals("Vigilante agregado con exito")) {
            Utilidades.Utilidades.mensajeExito(confirmacion, "Registro Exitoso.");
        } else {
            Utilidades.Utilidades.mensajeError("Vigilante ya registrado", "Error.");
        }
    }//GEN-LAST:event_btnRegVigilanteActionPerformed

    public String getIdentificacion() {
        identificacion = txtId.getText();
        return identificacion;
    }

    public void setIdentificacion(String identificacion) {
        this.identificacion = identificacion;
    }

    public String getNombre() {
        nombre = txtNombres.getText();
        return nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    public String getApellido() {
        apellido = txtApellidos.getText();
        return apellido;
    }

    public void setApellido(String apellido) {
        this.apellido = apellido;
    }

    public String getGenero() {
        if (rbFemenino.isSelected()) {
            genero = "Femenino";
        }
        if (rbMasculino.isSelected()) {
            genero = "Masculino";
        }
        if (rbOtro.isSelected()) {
            genero = "Otro";
        }
        return genero;
    }

    public void setGenero(String genero) {
        this.genero = genero;
    }

    public String getFechaNacimiento() {
        Date date = rSDateCalendar.getDate();
        fechaNacimiento = DateFormat.getDateInstance().format(date);
        return fechaNacimiento;
    }

    public void setFechaNacimiento(String fechaNacimiento) {
        this.fechaNacimiento = fechaNacimiento;
    }

    public String getEmpresa() {
        empresa = txtEmpresa.getText();
        return empresa;
    }

    public void setEmpresa(String empresa) {
        this.empresa = empresa;
    }

    public String getUsuario() {
        usuario = txtUsuario.getText();
        return usuario;
    }

    public void setUsuario(String usuario) {
        this.usuario = usuario;
    }

    public String getContrasenia() {
        contrasenia = txtContrasenia.getText();
        return contrasenia;
    }

    public void setContrasenia(String contrasenia) {
        this.contrasenia = contrasenia;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegVigilante;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel lbApellidos;
    private javax.swing.JLabel lbEmpresa;
    private javax.swing.JLabel lbFecNacimiento;
    private javax.swing.JLabel lbGenero;
    private javax.swing.JLabel lbIdentificacion;
    private javax.swing.JLabel lbNombres;
    private javax.swing.JLabel lbRegConductor;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JPanel pnlPrincipal;
    private com.toedter.calendar.JDateChooser rSDateCalendar;
    private javax.swing.JRadioButton rbFemenino;
    private javax.swing.JRadioButton rbMasculino;
    private javax.swing.JRadioButton rbOtro;
    private javax.swing.JTextField txtApellidos;
    private javax.swing.JTextField txtContrasenia;
    private javax.swing.JTextField txtEmpresa;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtNombres;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
