/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentacion;

import java.text.DateFormat;
import java.util.Date;
import negocio.GestorUsuario;
import negocio.Vigilante;

/**
 *
 * @author Personal
 */
public class GUIRegistrarVigilante extends javax.swing.JInternalFrame {

    private int cont;
    private String identificacion, nombre, apellido, genero, fechaNacimiento, empresa, usuario, contrasenia;
    private final GestorUsuario gestorVigilante = new GestorUsuario();

    public GUIRegistrarVigilante() {
        initComponents();
        mostrarLabel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlPrincipal = new javax.swing.JPanel();
        lbIdentificacion = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        lbvid = new javax.swing.JLabel();
        lbNombres = new javax.swing.JLabel();
        txtNombres = new javax.swing.JTextField();
        lbvNom = new javax.swing.JLabel();
        lbApellidos = new javax.swing.JLabel();
        txtApellidos = new javax.swing.JTextField();
        lbvApe = new javax.swing.JLabel();
        lbGenero = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        rbFemenino = new javax.swing.JRadioButton();
        rbMasculino = new javax.swing.JRadioButton();
        rbOtro = new javax.swing.JRadioButton();
        lbvfec2 = new javax.swing.JLabel();
        lbFecNacimiento = new javax.swing.JLabel();
        rSDateCalendar = new com.toedter.calendar.JDateChooser();
        lbvfec = new javax.swing.JLabel();
        lbEmpresa = new javax.swing.JLabel();
        txtEmpresa = new javax.swing.JTextField();
        lbvemp = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        lbvusu = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtContrasenia = new javax.swing.JTextField();
        lbvcontra = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnRegVigilante = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setClosable(true);
        setTitle("Registrar Vigilante");

        pnlPrincipal.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        pnlPrincipal.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Registro de Vigilante UNICAUCA", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tw Cen MT Condensed", 1, 14))); // NOI18N
        pnlPrincipal.setLayout(new java.awt.GridLayout(9, 3));

        lbIdentificacion.setBackground(new java.awt.Color(204, 204, 255));
        lbIdentificacion.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbIdentificacion.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbIdentificacion.setText("Identificación: ");
        pnlPrincipal.add(lbIdentificacion);
        pnlPrincipal.add(txtId);

        lbvid.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 18)); // NOI18N
        lbvid.setForeground(new java.awt.Color(255, 0, 0));
        lbvid.setText("Requerido");
        pnlPrincipal.add(lbvid);

        lbNombres.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbNombres.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbNombres.setText("Nombres: ");
        pnlPrincipal.add(lbNombres);
        pnlPrincipal.add(txtNombres);

        lbvNom.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 18)); // NOI18N
        lbvNom.setForeground(new java.awt.Color(255, 0, 0));
        lbvNom.setText("Requerido");
        pnlPrincipal.add(lbvNom);

        lbApellidos.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbApellidos.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbApellidos.setText("Apellidos: ");
        pnlPrincipal.add(lbApellidos);
        pnlPrincipal.add(txtApellidos);

        lbvApe.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 18)); // NOI18N
        lbvApe.setForeground(new java.awt.Color(255, 0, 0));
        lbvApe.setText("Requerido");
        pnlPrincipal.add(lbvApe);

        lbGenero.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbGenero.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbGenero.setText("Genero: ");
        pnlPrincipal.add(lbGenero);

        jPanel2.setLayout(new java.awt.GridLayout(1, 3));

        rbFemenino.setSelected(true);
        rbFemenino.setText("Femenino");
        jPanel2.add(rbFemenino);

        rbMasculino.setText("Masculino");
        jPanel2.add(rbMasculino);

        rbOtro.setText("Otro");
        jPanel2.add(rbOtro);

        pnlPrincipal.add(jPanel2);

        lbvfec2.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 18)); // NOI18N
        lbvfec2.setForeground(new java.awt.Color(255, 0, 0));
        pnlPrincipal.add(lbvfec2);

        lbFecNacimiento.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbFecNacimiento.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbFecNacimiento.setText("Fecha de Nacimiento: ");
        pnlPrincipal.add(lbFecNacimiento);
        pnlPrincipal.add(rSDateCalendar);

        lbvfec.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 18)); // NOI18N
        lbvfec.setForeground(new java.awt.Color(255, 0, 0));
        lbvfec.setText("Requerido");
        pnlPrincipal.add(lbvfec);

        lbEmpresa.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbEmpresa.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbEmpresa.setText("Empresa: ");
        pnlPrincipal.add(lbEmpresa);
        pnlPrincipal.add(txtEmpresa);

        lbvemp.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 18)); // NOI18N
        lbvemp.setForeground(new java.awt.Color(255, 0, 0));
        lbvemp.setText("Requerido");
        pnlPrincipal.add(lbvemp);

        lblUsuario.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblUsuario.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblUsuario.setText("Usuario: ");
        pnlPrincipal.add(lblUsuario);
        pnlPrincipal.add(txtUsuario);

        lbvusu.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 18)); // NOI18N
        lbvusu.setForeground(new java.awt.Color(255, 0, 0));
        lbvusu.setText("Requerido");
        pnlPrincipal.add(lbvusu);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Contraseña: ");
        pnlPrincipal.add(jLabel2);
        pnlPrincipal.add(txtContrasenia);

        lbvcontra.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 18)); // NOI18N
        lbvcontra.setForeground(new java.awt.Color(255, 0, 0));
        lbvcontra.setText("Requerido");
        pnlPrincipal.add(lbvcontra);
        pnlPrincipal.add(jLabel1);

        btnRegVigilante.setBackground(new java.awt.Color(204, 204, 255));
        btnRegVigilante.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnRegVigilante.setText("Registrar");
        btnRegVigilante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegVigilanteActionPerformed(evt);
            }
        });
        pnlPrincipal.add(btnRegVigilante);

        getContentPane().add(pnlPrincipal, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegVigilanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegVigilanteActionPerformed
        // TODO add your handling code here:
        String confirmacion;
        validarCampos();
        if (getCont() == 0) {
            String identificacion = getIdentificacion();
            String nombreV = getNombre();
            String apellidoV = getApellido();
            String generoV = getGenero();
            String fechaNacimientoV = getFechaNacimiento();
            String empresaV = getEmpresa();
            String usuarioV = getUsuario();
            String contraseniaV = getContrasenia();
            Vigilante vigilante = new Vigilante(identificacion, nombreV, apellidoV, generoV, fechaNacimientoV, empresaV, usuarioV, contraseniaV);
            confirmacion = gestorVigilante.registrarVigilante(vigilante);
            if (confirmacion.equals("Vigilante agregado con exito")) {
                Utilidades.Utilidades.mensajeExito(confirmacion, "Registro Exitoso.");
            } else {
                Utilidades.Utilidades.mensajeError("Vigilante ya registrado", "Error.");
            }
        }
    }//GEN-LAST:event_btnRegVigilanteActionPerformed

    public String getIdentificacion() {
        identificacion = txtId.getText();
        return identificacion;
    }

    public void setIdentificacion(String identificacion) {
        this.identificacion = identificacion;
    }

    public String getNombre() {
        nombre = txtNombres.getText();
        return nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    public String getApellido() {
        apellido = txtApellidos.getText();
        return apellido;
    }

    public void setApellido(String apellido) {
        this.apellido = apellido;
    }

    public String getGenero() {
        if (rbFemenino.isSelected()) {
            genero = "Femenino";
        }
        if (rbMasculino.isSelected()) {
            genero = "Masculino";
        }
        if (rbOtro.isSelected()) {
            genero = "Otro";
        }
        return genero;
    }

    public void setGenero(String genero) {
        this.genero = genero;
    }

    public String getFechaNacimiento() {
        Date date = rSDateCalendar.getDate();
        fechaNacimiento = DateFormat.getDateInstance().format(date);
        return fechaNacimiento;
    }

    public int getCont() {
        return cont;
    }

    public void setFechaNacimiento(String fechaNacimiento) {
        this.fechaNacimiento = fechaNacimiento;
    }

    public String getEmpresa() {
        empresa = txtEmpresa.getText();
        return empresa;
    }

    public void setEmpresa(String empresa) {
        this.empresa = empresa;
    }

    public String getUsuario() {
        usuario = txtUsuario.getText();
        return usuario;
    }

    public void setUsuario(String usuario) {
        this.usuario = usuario;
    }

    public String getContrasenia() {
        contrasenia = txtContrasenia.getText();
        return contrasenia;
    }

    public void setContrasenia(String contrasenia) {
        this.contrasenia = contrasenia;
    }

    public void validarCampos() {
        if (txtId.getText().equals("")) {
            lbvid.setVisible(true);
            cont++;
        } else {
            lbvid.setVisible(false);
        }
        if (getNombre().equals("")) {
            lbvNom.setVisible(true);
            cont++;
        } else {
            lbvNom.setVisible(false);
        }
        if (getApellido().equals("")) {
            lbvApe.setVisible(true);
            cont++;
        } else {
            lbvApe.setVisible(false);
        }
        if (rSDateCalendar.getDate() == null) {
            lbvfec.setVisible(true);
            cont++;
        } else {
            lbvfec.setVisible(false);
        }
        if (getEmpresa().equals("")) {
            lbvemp.setVisible(true);
            cont++;
        } else {
            lbvemp.setVisible(false);
        }
        if (getUsuario().equals("")) {
            lbvusu.setVisible(true);
            cont++;
        } else {
            lbvusu.setVisible(false);
        }
        if (getContrasenia().equals("")) {
            lbvcontra.setVisible(true);
            cont++;
        } else {
            lbvcontra.setVisible(false);
        }
    }

    public void mostrarLabel() {
        lbvid.setVisible(false);
        lbvNom.setVisible(false);
        lbvApe.setVisible(false);
        lbvfec.setVisible(false);
        lbvemp.setVisible(false);
        lbvusu.setVisible(false);
        lbvcontra.setVisible(false);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegVigilante;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lbApellidos;
    private javax.swing.JLabel lbEmpresa;
    private javax.swing.JLabel lbFecNacimiento;
    private javax.swing.JLabel lbGenero;
    private javax.swing.JLabel lbIdentificacion;
    private javax.swing.JLabel lbNombres;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JLabel lbvApe;
    private javax.swing.JLabel lbvNom;
    private javax.swing.JLabel lbvcontra;
    private javax.swing.JLabel lbvemp;
    private javax.swing.JLabel lbvfec;
    private javax.swing.JLabel lbvfec2;
    private javax.swing.JLabel lbvid;
    private javax.swing.JLabel lbvusu;
    private javax.swing.JPanel pnlPrincipal;
    private com.toedter.calendar.JDateChooser rSDateCalendar;
    private javax.swing.JRadioButton rbFemenino;
    private javax.swing.JRadioButton rbMasculino;
    private javax.swing.JRadioButton rbOtro;
    private javax.swing.JTextField txtApellidos;
    private javax.swing.JTextField txtContrasenia;
    private javax.swing.JTextField txtEmpresa;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtNombres;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
