/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentacion;

import java.util.ArrayList;
import javax.swing.JButton;
import javax.swing.table.DefaultTableModel;
import negocio.GestorVehiculoPersona;
import negocio.Multa;
import negocio.Render;
import negocio.Vehiculo;

/**
 *
 * @author Personal
 */
public class GUIVerMultas extends javax.swing.JInternalFrame {

    /**
     * Creates new form GUIVerMultas
     */
    public GUIVerMultas(String prmPlaca) {
        initComponents();
        verMultas(prmPlaca);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlMultas = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblMultas = new javax.swing.JTable();

        setClosable(true);

        pnlMultas.setBorder(javax.swing.BorderFactory.createTitledBorder("Reporte de Multas"));
        pnlMultas.setLayout(new java.awt.GridLayout());

        tblMultas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Descripcion", "Fecha"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblMultas);

        pnlMultas.add(jScrollPane1);

        getContentPane().add(pnlMultas, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void verMultas(String prmMulta){
        GestorVehiculoPersona gestor = new GestorVehiculoPersona();
        ArrayList<Multa> objMultas = null;
        objMultas = gestor.verMultas(prmMulta);
        if (objMultas != null){
            cargarMultas(objMultas);
        }
    }
    public void cargarMultas(ArrayList<Multa> prmMultas){
        DefaultTableModel model = (DefaultTableModel) tblMultas.getModel();
        Object rowData[] = new Object[2];
        for (Multa mul : prmMultas) {
            rowData[0] = mul.getMulDescripcion();
            rowData[1] = mul.getMulFecha();
            model.addRow(rowData);
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel pnlMultas;
    private javax.swing.JTable tblMultas;
    // End of variables declaration//GEN-END:variables
}
